<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 30px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            text-transform: uppercase;
        }

        .header h2 {
            margin: 5px 0;
            font-size: 18px;
            font-weight: normal;
        }

        .meta-info {
            text-align: right;
            font-size: 12px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
            margin-bottom: 30px;
        }

        th,
        td {
            border: 1px solid #333;
            padding: 6px;
            text-align: left;
        }

        th {
            background: #eaeaea;
        }

        .signature {
            margin-top: 40px;
            text-align: right;
        }

        .signature .name {
            margin-top: 60px;
            font-weight: bold;
            font-size: 14px;
        }

        .signature .title {
            font-size: 12px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Acme Corporation</h1>
        <h2>Product Inventory Report</h2>
    </div>

    <div class="meta-info">
        Date Generated: {{ now()->format('d M Y, H:i') }}<br>
        Generated By: System Admin (Dummy)
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>ID</th>
                <th>Prodcut Name</th>
                <th>Unit</th>
                <th>Type</th>
                <th>Information</th>
                <th>Qty</th>
                <th>Producer</th>
                <th>Updatet at</th>
                <th>Created at</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $index => $product)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $product->id }}</td>
                <td>{{ $product->product_name }}</td>
                <td>{{ $product->unit }}</td>
                <td>{{ $product->type }}</td>
                <td>{{ $product->information }}</td>
                <td>{{ $product->qty }}</td>
                <td>{{ $product->producer }}</td>
                <td>{{ $product->updated_at }}</td>
                <td>{{ $product->created_at }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signature">
        <p class="name">John Doe</p>
        <p class="title">Head of Inventory</p>
    </div>
</body>

</html>